add-charts
UCLALibrary/oral-history pull request #65
Opened 2023-08-05 04:07 UTC by aprilrieger

Adding charts and templates with values file, still need to integrate the pvc

2023-08-11 21:50 UTC, sgurnick requested changes
Can we consolidate the three separate external-secret template files for the db, solr, and negative-captcha into one file?

Also, can we parameterize the external-secret template file so we can reference values from either the `values` file or pull them in from `_helpers.tpl`.

The new consolidated external-secrets file could look something like this: 
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-externalsecret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshinterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "chart.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: negative-captcha-secret
      remoteRef:
        key: {{ .Values.externalSecrets.env.negative-captcha-secret }}
    - secretKey: database-password
      remoteRef:
        key: {{ .Values.externalSecrets.env.database-password }}
    - secretKey: solr-admin-password
      remoteRef:
        key: {{ .Values.externalSecrets.env.solr-admin-password }}
```

2023-08-11 21:56 UTC, sgurnick requested changes
Since we have the option to enable/disable the use of the dependent solr and postgres charts, can we create values that allow us to identify the the hostname of the "external" solr or postgres system? 

For example:
```
postgresql:
  enabled: false
  # If postgresql.enabled is false, then
  #   * set postgresqlHostname to external postgresql FQDN
  # postgresqlHostname: external-shoreline-postgresql-fqdn


solr:
  enabled: false
  # To use an external/preexisting solr, set solr.enabled to false, then
  #   * set solrHostname to external solr FQDN
  #   * set solrPort to external solr port
  # solrHostname: external-shoreline-solr-fqdn
  # solrPort: "8983"
```

2023-08-16 15:59 UTC, sgurnick commented on chart/templates/oral-history-env.yaml
@aprilrieger: In this `ConfigMap` it's not evident where we define the environment variables for the postgres host and the solr host, regardless if these resources are enabled. 

Do we need to add something like:
`POSTGRES_HOST: {{ template "chart.postgresql.host" . }}`
`SOLR_HOST: {{ template "chart.solr.host" . }}`

2023-08-16 16:14 UTC, aprilrieger commented on chart/templates/oral-history-env.yaml
@sgurnick Yes absolutely we do, thank you, I don't know how I overlooked this, thank you for the through review!

2023-08-16 16:29 UTC, sgurnick requested changes

2023-08-16 16:29 UTC, sgurnick commented on chart/templates/oral-history-env.yaml
Some other items I noticed that need adjustments in the `ConfigMap`:

- POSTGRES_DB should be changed to:
`POSTGRES_DB: {{  .Values.postgresql.postgresqlDatabase }}`
- POSTGRES)USER should be changed to:
`POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername }}`

Probably also worth taking a look throughout the `values` file to see if anything else needs to be defined here.

2023-08-16 17:35 UTC, sgurnick requested changes

2023-08-16 17:42 UTC, aprilrieger commented on chart/values.yaml
> +  repository: ghcr.io/or-whatever-container-registry-you-use
For me, at this point it is your external image repository needing to get hooked up. And yes you can default to latest, but depending on how you set up the deployment you can over-ride it.

We deploy from a script that sets the DEPLOY_TAG values dynamically through GitHub actions, and pulls from the ghcr.io, but I know you use an external image registry, and will be integrating that with ArgoCD for deployments?

2023-08-16 17:55 UTC, sgurnick commented on chart/values.yaml
> +  repository: ghcr.io/or-whatever-container-registry-you-use
Ok - then it looks like we'll use our docker hub `uclalibrary/oral-history` repo for the oralhistory image. We can add that into our env-specific values file along with the appropriate tag. 

As for the tagging, have you and your team just been tagging images with `test`, `staging`, and `latest`? 

We will use ArgoCD as our deployment mechanism into our K8s cluster and having versioned tags will be important for us. This seems like it's worth more discussion (outside of this review process) to ensure we can come-up with a deployment process that works for everyone. 

As for this initial helm chart review, I think we're good.

2023-08-16 17:56 UTC, sgurnick approved these changes

2023-08-16 18:09 UTC, aprilrieger commented on chart/values.yaml
> +  repository: ghcr.io/or-whatever-container-registry-you-use
As a consulting agency that has multiple clients and multiple teams working across pipeline's together, we tag our deployment images with the actual sha, shortened to 7 (because we moved form gitlab). This helps us de-mystify it all for the developers so they can correlate the sha to the image deployed and be able to take troubleshooting action. 

Our deployment strategy through github actions is based on the environment we are deploying to.

I'll post Hyku's public repo as an example:
https://github.com/samvera/hyku/tree/main/ops <-- values files per environment
https://github.com/samvera/hyku/blob/main/bin/helm_deploy <--- deploy script
That tie to our actions repo that houses our reusable workflows we have versioned by release (this is v0.0.13): 
https://github.com/scientist-softserv/actions/blob/v0.0.13/.github/workflows/deploy.yaml
https://github.com/scientist-softserv/actions/blob/v0.0.13/.github/workflows/build.yaml

Our strategy is quite different than the one your institution currently utilizes, so I am not sure if that would be necessary for your use-case, but I could be wrong. 

Let me know if you have any more questions.

2023-08-25 20:45 UTC, merged